[tool.pytest.ini_options]
markers = [
    "time_to_sec: Change time string to float",
    "sec_to_time: Change float to time string",
    "recipe_loading: Loading of the recipe object",
    "crafter_loading: Loading of the crafter object",
    "item: Methods of the item object",
    "inventory: Methods of the inventory object",
    "debug: Debug functions",
    "loading: Loading of files",
    "print: Printing a clearable text",
    "print: Printing and clearing a clearable text",
]
addopts = "-p no:warnings --cov=. --cov-report term-missing:skip-covered"